-- Queue Management System - Create Queue Table Script
-- Database: HOSPDB
-- Execute this script to create the QUEUE_MASTER table

-- Drop table if exists (optional)
-- DROP TABLE QUEUE_MASTER;

-- Create the queue table
CREATE TABLE QUEUE_MASTER (
    QUEUE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    PATIENT_ID INTEGER NOT NULL,
    AADHAR_NO CHAR(12) NOT NULL,
    PATIENT_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'WAITING',
    QUEUE_NUMBER INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (QUEUE_ID)
);

-- Create index for faster department queries
CREATE INDEX IDX_QUEUE_DEPT ON QUEUE_MASTER(DEPARTMENT);
CREATE INDEX IDX_QUEUE_STATUS ON QUEUE_MASTER(STATUS);

-- Verify table creation
SELECT TABNAME, COLNAME, TYPENAME, LENGTH 
FROM SYSCAT.COLUMNS 
WHERE TABNAME = 'QUEUE_MASTER' 
ORDER BY COLNO;

-- Display message
VALUES ('QUEUE_MASTER table created successfully!');
