-- Migration script to change primary key from AADHAR_NO to CUSTID
-- This approach creates a new table with the correct structure and migrates data

-- Step 1: Create new table with CUSTID as primary key
CREATE TABLE PATIENT_MASTER_NEW (
    CUSTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    AADHAR_NO VARCHAR(12) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    AGE INTEGER,
    GENDER VARCHAR(10),
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(15),
    DEPARTMENT_VISITED VARCHAR(500) NOT NULL,
    VISIT_COUNT INTEGER DEFAULT 1,
    PRIMARY KEY (CUSTID),
    UNIQUE (AADHAR_NO)
);

-- Step 2: Copy existing data from old table
INSERT INTO PATIENT_MASTER_NEW (AADHAR_NO, NAME, AGE, GENDER, ADDRESS, PHONE, DEPARTMENT_VISITED, VISIT_COUNT)
SELECT AADHAR_NO, NAME, AGE, GENDER, ADDRESS, PHONE, DEPARTMENT_VISITED, VISIT_COUNT
FROM PATIENT_MASTER;

-- Step 3: Drop old table
DROP TABLE PATIENT_MASTER;

-- Step 4: Rename new table to original name
RENAME TABLE PATIENT_MASTER_NEW TO PATIENT_MASTER;

COMMIT;
